# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
# Use a package of configuration called an orb.
jobs:
  setup:
    docker:
      - image: openjdk:11.0.3
    steps:
      - run:
          name: just a test!!
          command: |
            echo "hello!!"
workflows:
  version: 2
  setup:
    jobs:
      - setup