# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
# Use a package of configuration called an orb.
jobs:
  one:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch-node-browsers-legacy
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir my_workspace
      - run: java -version
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
  two:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch-node-browsers-legacy
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - attach_workspace:
          at: my_workspace
      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one