version: 2
defaults: &defaults
  docker:
    - image: circleci/openjdk:11.0.3-jdk-stretch-node-browsers-legacy
  working_directory: ~
  environment:
    PROTEST_APP_NAME: "CIRCLECI_TEST"
    PROTEST_APP_OWNER_NAME: "LEVANANHTU"
    PROTEST_APP_OWNER_AGE: "22"
    PROTEST_APP_OWNER_CODENAME: "LVAT"
jobs:
  setup:
    <<: *defaults
    steps:
      - run: echo 123456
workflows:
  version: 2
  haha:
    jobs:
      - setup