# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
# Use a package of configuration called an orb.
jobs:
  one:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch-node-browsers-legacy
    steps:
      - checkout
      - run: echo "A first hello"
      - run: pwd
      - run: mkdir lvat01
      - run: sleep 25
  two:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch-node-browsers-legacy
    steps:
      - checkout
      - run: echo "A more famillar hi"
      - run: mkdir lvat02
      - run: sleep 15
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          type: approval
          requires:
            - one