defaults: &defaults
  docker:
    - image: openjdk:11.0.3-jdk
  working_directory: ~
  run: echo "123456789"
version: 2
jobs:
  pre_build_setup:
    <<: *defaults
    steps:
      - run: curl https://downloads.tableau.com/esdalt/2018.1.0/tableau-tabcmd-2018-1-0_all.deb --output tableau-tabcmd-2018-1-0_all.deb
      - run: sudo apt-get install ./tableau-tabcmd-2018-1-0_all.deb
      - run: tabcmd version
      - run: pwd
      - run: ls -al

workflows:
  version: 2
  haha:
    jobs:
      - pre_build_setup