# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
# Use a package of configuration called an orb.
jobs:
  one:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch-node-browsers-legacy
    steps:
      - checkout
      - run: echo "A first hello"
      - run: pwd
      - run: mkdir lvat01
      - run: sleep 25
  two:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch-node-browsers-legacy
    steps:
      - run:
          - name: Checkout
          - command: checkout
      - run:
          - name: print some message
          - command: echo "A more famillar hi"
      - run:
          - name: create lvat02 dir
          - command: mkdir lvat02
      - run:
          - name: list all directory and file
          - command: ls -al
      - run:
          - name: print current working directory
          - command: pwd
      - run:
          - name: sleep for 15 seconds
          - command: sleep 15
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one