defaults: &defaults
  docker:
    - image: circleci/openjdk:11.0.3-jdk-stretch-node-browsers-legacy
  working_directory: ~
  environment:
    PROTEST_SPRING_DATASOURCE_USERNAME: "LVAT"
    PROTEST_SPRING_DATASOURCE_PASSWORD: "123456"
version: 2
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - circleci-test-{{ .Branch }}-{{ checksum "pom.xml" }}
            - circleci-test-{{ .Branch }}
            - circleci-test
      - run:
          name: print maven folder
          command: ls ~/.m2/repository/ -al
      - run:
          name: inject env var to config file
          command: |
            sed -i 's/PROTEST_SPRING_DATASOURCE_USERNAME/'${PROTEST_SPRING_DATASOURCE_USERNAME}'/g' ~/project/src/main/resources/application.properties
            sed -i 's/PROTEST_SPRING_DATASOURCE_PASSWORD/'${PROTEST_SPRING_DATASOURCE_PASSWORD}'/g' ~/project/src/main/resources/application.properties
      - run:
          name: test mvn
          command: mvn --version
      - run:
          name: build
          command: mvn install
      - run:
          name: print target folder
          command: ls target/
      - run:
          name: print maven folder again
          command: ls ~/.m2/repository/ -al
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-test-{{ .Branch }}-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
  print:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: print config file
          command: echo "$(cat ~/project/src/main/resources/application.properties)!"

workflows:
  version: 2
  haha:
    jobs:
      - setup
      - print:
          requires:
            - setup